export const FETCH_MATCHES = 'FETCH_MATCHES';
export const FETCH_THREAD_LIST = 'FETCH_THREAD_LIST';
export const FETCH_NEW_MESSAGE = 'FETCH_NEW_MESSAGE';
export const FETCH_EARLIER_MESSAGES = 'FETCH_EARLIER_MESSAGES';
export const CREATE_PROFILE = 'CREATE_PROFILE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const MODIFY_USER_PROFILE = 'MODIFY_USER_PROFILE';
